//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinHeThong
    {
        public int MaTT { get; set; }
        public string GioiThieu { get; set; }
        public string Hotline { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
    }
}
